### ISSUE TITLE
Saving null values in a column

### ISSUE THREAD

**Issue by tgmcguire** [eflorea/rpc#15]
Hi there,

It would be wonderful if a raw `null` value could be saved into a column. To avoid breaking any existing implementations, you might consider honoring an optional "magic word" constant, like `NULL_VALUE`. If that constant is defined (perhaps in `index.php`), and passed to the magic call, then a raw `null` value will be saved instead of `string(null)`, `int(0)`, or `bool(false)`.

Thanks! =)

**Comment by eflorea** [comment]
This is solved in #16
